version: "3"
services:
  nagios-monitor:
    container_name: nagios-monitor
    image: louiseschmidtgen/expensify-infrastructure-challenge:nagios-monitor
    # platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8083:80"
      # - "5666:5666" # Expose port 5666 for NRPE
