---
- name: Deploy Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Install Docker and Docker Compose
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - docker-compose
      tags: [docker]

    - name: Copy Docker Compose file
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
      tags: [docker]

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
      tags: [docker]
