---
- name: Deploy Docker Compose
  hosts: all
  become: yes
  tasks:
    # - name: Update package manager cache
    #   apt:
    #     update_cache: yes

    # - name: Install Docker and Docker Compose
    #   apt:
    #     name: ['docker', 'docker-compose']
    #     state: present
    #   tags: [docker]
    # - name: Create custom network
    #   command: docker network create custom_network
    - name: Start Docker Daemon
      become: yes
      service:
        name: docker
        state: started

    - name: Create custom network
      docker_network:
        name: my_network
        driver: bridge
      tags: [docker]

    - name: Create expensify user
      user:
        name: expensify
        state: present

    - name: Add expensify user to sudo group
      user:
        name: expensify
        groups: sudo
        append: yes
      become: yes

    - name: Create .ssh directory for expensify user
      file:
        path: "/home/expensify/.ssh"
        state: directory
        owner: expensify
        group: expensify
        mode: '0700'

    - name: Ensure authorized keys are present for expensify user
      authorized_key:
        user: expensify
        state: present
        key: "{{ lookup('file', '../vars/authorized_keys.txt') }}"
      become: yes
    
    - name: Configure SSH
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
      notify:
        - restart sshd
  handlers:
      - name: restart sshd
        service:
          name: sshd
          state: restarted


- name: Deploy Server A Service
  hosts: server-a
  become: yes
  roles:
    - server-a
  tasks:

    - name: Copy server-a folder to the server
      synchronize:
        src: ../server-a
        dest: /home/expensify/
        delete: yes
        
    - name: Build and Deploy Server A container
      command: docker-compose -f /home/expensify/server-a/docker-compose.yml up -d#-d server-a
      tags: [server-a, docker]
    