- name: Deploy Server A Service
  hosts: server-a
  become: yes
  roles:
    - server-a
  tasks:
    - name: Ensure server-a directory exists
      file:
        path: /home/ubuntu/server-a
        state: directory

    - name: Copy server-a folder to the server
      synchronize:
        src: ./server-a
        dest: /home/ubuntu/server-a
        delete: yes
        
    - name: Build and Deploy Server A container
      command: docker-compose -f ./docker-compose.yml up -d server-a
      args:
        chdir: /home/ubuntu/
      tags: [server-a, docker]
