services:
  server-a:
    container_name: server-a
    image: server-a
    build:
      context: ./server-a
      dockerfile: Dockerfile
    restart: always  
    ports:
      - "80:80"
    stdin_open: true 
    tty: true
    # volumes:
    #   - /server-a/Volumes/static:/index
    #   - /server-a/nginx.conf:/etc/nginx/conf.d/default.conf


  server-b:
    container_name: server-b
    image: server-b
    build:
      context: ./server-b
      dockerfile: Dockerfile
    restart: always  
    ports:
      - "80:80"
    stdin_open: true 
    tty: true
  load-balancer:
    container_name: load-balancer
    image: load-balancer
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    stdin_open: true 
    tty: true    
    depends_on:
      - server-a
      - server-b 
  nagios-monitor:
    container_name: nagios-monitor
    image: nagios-monitor
    build:
      context: ./nagios-monitor
      dockerfile: Dockerfile
    stdin_open: true 
    tty: true
    depends_on:
      - server-a
      - server-b
      - load-balancer

