version: "3"
services:
  server-a:
    container_name: server-a
    image: louiseschmidtgen/expensify-infrastructure-challenge:server-a
    restart: always
    ports:
      - "8080:80"
      - "5668:5666" # Expose port 5666 for NRPE
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == louiseschmidtgen1.remotechallenge

  server-b:
    container_name: server-b
    image: louiseschmidtgen/expensify-infrastructure-challenge:server-b
    restart: always
    ports:
      - "8081:80"
      - "5667:5666" # Expose port 5666 for NRPE
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == louiseschmidtgen2.remotechallenge
  load-balancer:
    container_name: load-balancer
    image: louiseschmidtgen/expensify-infrastructure-challenge:load-balancer
    ports:
      - "60000-65000:60000-65000"
      - "5666:5666"
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == louiseschmidtgen4.remotechallenge
  nagios-monitor:
    container_name: nagios-monitor
    image: louiseschmidtgen/expensify-infrastructure-challenge:nagios-monitor
    stdin_open: true
    tty: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == louiseschmidtgen3.remotechallenge
    ports:
      - "8083:80"
      # - "5666:5666" # Expose port 5666 for NRPE
