services:
  server-a:
    container_name: server-a
    image: server-a
    build:
      context: ./server-a
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    stdin_open: true
    tty: true

  server-b:
    container_name: server-b
    image: server-b
    build:
      context: ./server-b
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
    stdin_open: true
    tty: true
  load-balancer:
    container_name: load-balancer
    image: load-balancer
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    ports:
      - "60000-65000:60000-65000"
      - "5666:5666"
    stdin_open: true
    tty: true
    depends_on:
      - server-a
      - server-b
  nagios-monitor:
    container_name: nagios-monitor
    image: nagios-monitor
    # platform: linux/arm64/v8
    build:
      context: ./nagios-monitor
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8083:80"
    depends_on:
      - server-a
      - server-b
      - load-balancer
