services:
  serverA:
    container_name: serverA
    image: serverA
    build:
      context: .
      dockerfile: Dockerfile
    restart: always  
    ports:
      - "80:80"
    # volumes:
      # - ./data:/srv
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf


  serverB:
    container_name: serverB
    image: serverB
    build:
      context: .
      dockerfile: Dockerfile
    restart: always  
    ports:
      - "80:80"
  load-balancer:
     depends_on:
      - serverA
      - serverB 
  nagios-monitor:
    depends_on:
      - serverA
      - serverB
      - nagios-monitor

