version: "3"
services:
  server-b:
    container_name: server-b
    image: server-b
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
      - "5667:5666" # Expose port 5666 for NRPE
    stdin_open: true
    tty: true
    networks:
      - custom_network
networks:
  custom_network:
    external:
      name: custom_network
